Repository openshift/cluster-update-keys, pull requests merged in 2019-05, with the labels that each got.

#4 Add Red Hat public keys and storage locations to signing
  Makefile
  keys/verifier-public-key-redhat-beta-2
  keys/verifier-public-key-redhat-release-auxiliary
  manifests.rhel/0000_00_cluster-update-keys_configmap.yaml
  manifests.rhel/0000_90_cluster-update-keys_configmap.yaml
  stores/store-openshift-official-release
  stores/store-openshift-official-release-mirror
Labels: approved, lgtm, size/L

#6 Update Red Hat output to not create two files
  Makefile
  manifests.rhel/0000_00_cluster-update-keys_configmap.yaml
  manifests.rhel/0000_90_cluster-update-keys_configmap.yaml
Labels: approved, lgtm, size/XS

#9 Product image does not have operator label
  Dockerfile.rhel
  Makefile
  manifests.rhel/0000_00_cluster-update-keys_configmap.yaml
  manifests.rhel/0000_90_cluster-update-keys_configmap.yaml
Labels: approved, lgtm, size/XS

#8 Product image does not have operator label
  Dockerfile.rhel
Labels: approved, lgtm, size/XS

#11 Concatenate keys into a single armored block
  Makefile
  manifests.rhel/0000_90_cluster-update-keys_configmap.yaml
Labels: approved, lgtm, size/M

#12 Only include the beta key. Not the beta and the release2 key
  Makefile
  manifests.rhel/0000_90_cluster-update-keys_configmap.yaml
Labels: lgtm, size/M

#13 Concatenate keys into a single armored block
  Makefile
  manifests.rhel/0000_90_cluster-update-keys_configmap.yaml
Labels: approved, do-not-merge/hold, size/M

#14 mktemp -t requires a template on linux
  Makefile
Labels: approved, lgtm, size/XS
